# Docker Compose Definitions for local Developer Environment
version: "3.3"
services: 
  kafka: 
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: "34.212.248.28"
      KAFKA_ADVERTISED_PORT: 5002
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "messages:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LOG_DIRS: "/kafka/kafka-logs"
    expose: 
      - 9092
    image: "wurstmeister/kafka:0.10.1.0"
    ports: 
      - "5002:9092"
    volumes:
      - /home/ec2-user/kafka/kafka-data:/kafka/kafka-logs
  zookeeper: 
    image: wurstmeister/zookeeper
    ports: 
      - "5001:2181"
