# Docker Compose Definitions for local Developer Environment
version: "3.3"
services: 
  zookeeper:
    image: wurstmeister/zookeeper
    deploy:
      replicas: 2
    ports:
      - "5001:2181"
  kafka: 
    image: wurstmeister/kafka:latest
    ports:
      - "5002:9094"
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "messages:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LOG_DIRS: "/kafka/kafka-logs"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://34.212.248.28:5002
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ec2-user/kafka/kafka-data:/kafka/kafka-logs
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 2
